# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [1]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import pdist, squareform

In [2]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [3]:
data.head()

CustomerID FirstName   LastName  SalesID  ProductID           ProductName  \
0       61288      Rosa   Andersen   134196        229  Bread - Hot Dog Buns   
1       77352     Myron     Murray  6167892        229  Bread - Hot Dog Buns   
2       40094     Susan  Stevenson  5970885        229  Bread - Hot Dog Buns   
3       23548    Tricia    Vincent  6426954        229  Bread - Hot Dog Buns   
4       78981     Scott      Burch   819094        229  Bread - Hot Dog Buns   

   Quantity  
0        16  
1        20  
2        11  
3         6  
4        20

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [4]:
data_step1=data.groupby(["CustomerID", "ProductName"])["Quantity"].sum()
# No sé si se refiere a esto
data_step1

CustomerID  ProductName                  
33          Apricots - Dried                  1
            Assorted Desserts                 1
            Bandage - Flexible Neon           1
            Bar Mix - Pina Colada, 355 Ml     1
            Beans - Kidney, Canned            1
                                             ..
98200       Vol Au Vents                     50
            Wasabi Powder                    25
            Wine - Fume Blanc Fetzer         25
            Wine - Hardys Bankside Shiraz    25
            Yogurt - French Vanilla          25
Name: Quantity, Length: 63628, dtype: int64

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [5]:

table = pd.pivot_table(data, values = "Quantity", index=["ProductName"], columns = ["CustomerID"], aggfunc= np.sum)
table.fillna(0, inplace=True)
table.head()


CustomerID                         33     200    264    356    412    464    \
ProductName                                                                   
Anchovy Paste - 56 G Tube            0.0    0.0    0.0    0.0    0.0    0.0   
Appetizer - Mini Egg Roll, Shrimp    0.0    0.0    0.0    0.0    0.0    0.0   
Appetizer - Mushroom Tart            0.0    0.0    0.0    0.0    0.0    0.0   
Appetizer - Sausage Rolls            0.0    0.0    0.0    0.0    0.0    0.0   
Apricots - Dried                     1.0    0.0    0.0    0.0    1.0    0.0   

CustomerID                         477    639    649    669    ...  97697  \
ProductName                                                    ...          
Anchovy Paste - 56 G Tube            0.0    1.0    0.0    0.0  ...    0.0   
Appetizer - Mini Egg Roll, Shrimp    0.0    0.0    0.0    0.0  ...   25.0   
Appetizer - Mushroom Tart            0.0    1.0    0.0    0.0  ...   25.0   
Appetizer - Sausage Rolls            0.0    0.0    0.0    0.0  ...    0.0   
Apricots - Dried                     0.0    0.0    0.0    0.0  ...    0.0   

CustomerID                         97753  97769  97793  97900  97928  98069  \
ProductName                                                                   
Anchovy Paste - 56 G Tube           25.0    0.0    0.0    0.0    0.0    0.0   
Appetizer - Mini Egg Roll, Shrimp   25.0    0.0    0.0    0.0    0.0    0.0   
Appetizer - Mushroom Tart            0.0    0.0    0.0    0.0    0.0    0.0   
Appetizer - Sausage Rolls            0.0    0.0    0.0   25.0   25.0   25.0   
Apricots - Dried                    25.0    0.0    0.0    0.0    0.0    0.0   

CustomerID                         98159  98185  98200  
ProductName                                             
Anchovy Paste - 56 G Tube            0.0    0.0    0.0  
Appetizer - Mini Egg Roll, Shrimp    0.0    0.0    0.0  
Appetizer - Mushroom Tart            0.0   25.0    0.0  
Appetizer - Sausage Rolls            0.0   25.0    0.0  
Apricots - Dried                     0.0    0.0    0.0  

[5 rows x 1000 columns]

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [6]:
from scipy.spatial.distance import pdist, squareform
distances = pdist(table.T, 'euclidean')
matrix = squareform(distances)
print(matrix)
matrix_df = pd.DataFrame(1/(1+squareform(pdist(table.T, 'euclidean'))), index = table.columns, columns=table.columns)
matrix_df.head()

[[  0.          11.91637529  10.48808848 ... 228.62851966 239.
  229.77380181]
 [ 11.91637529   0.          11.74734012 ... 228.01096465 239.03765394
  229.70415756]
 [ 10.48808848  11.74734012   0.         ... 228.08112592 238.26665734
  229.77380181]
 ...
 [228.62851966 228.01096465 228.08112592 ...   0.         304.13812651
  305.16389039]
 [239.         239.03765394 238.26665734 ... 304.13812651   0.
  303.10889132]
 [229.77380181 229.70415756 229.77380181 ... 305.16389039 303.10889132
    0.        ]]


CustomerID     33        200       264       356       412       464    \
CustomerID                                                               
33          1.000000  0.077421  0.087047  0.081800  0.080634  0.082709   
200         0.077421  1.000000  0.078448  0.076435  0.073693  0.075255   
264         0.087047  0.078448  1.000000  0.080070  0.081800  0.080350   
356         0.081800  0.076435  0.080070  1.000000  0.076435  0.078187   
412         0.080634  0.073693  0.081800  0.076435  1.000000  0.078711   

CustomerID     477       639       649       669    ...     97697     97753  \
CustomerID                                          ...                       
33          0.074573  0.083020  0.081503  0.080070  ...  0.004811  0.004669   
200         0.075956  0.076435  0.077674  0.076923  ...  0.004824  0.004681   
264         0.076923  0.080634  0.082100  0.078448  ...  0.004822  0.004674   
356         0.075025  0.082403  0.077171  0.075956  ...  0.004816  0.004671   
412         0.075025  0.082403  0.078187  0.078448  ...  0.004810  0.004702   

CustomerID     97769     97793     97900     97928     98069     98159  \
CustomerID                                                               
33          0.004412  0.005019  0.004312  0.004515  0.004583  0.004355   
200         0.004431  0.005047  0.004311  0.004521  0.004614  0.004367   
264         0.004416  0.005035  0.004322  0.004543  0.004595  0.004365   
356         0.004416  0.005038  0.004310  0.004526  0.004578  0.004365   
412         0.004414  0.005034  0.004318  0.004530  0.004578  0.004367   

CustomerID     98185     98200  
CustomerID                      
33          0.004167  0.004333  
200         0.004166  0.004335  
264         0.004179  0.004333  
356         0.004175  0.004339  
412         0.004177  0.004349  

[5 rows x 1000 columns]

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [7]:
similarities = matrix_df[264].sort_values(ascending = False)[1:6]
lst_simi = list(similarities.index)
print(lst_simi)
similarities

[1008, 2617, 1072, 33, 3535]


CustomerID
1008    0.088152
2617    0.088152
1072    0.087410
33      0.087047
3535    0.086333
Name: 264, dtype: float64

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [8]:
data_step5 = data_step1.loc[lst_simi]
data_step5

CustomerID  ProductName                   
33          Apricots - Dried                  1
            Assorted Desserts                 1
            Bandage - Flexible Neon           1
            Bar Mix - Pina Colada, 355 Ml     1
            Beans - Kidney, Canned            1
                                             ..
3535        Tray - 16in Rnd Blk               1
            Wanton Wrap                       1
            Wine - Blue Nun Qualitatswein     1
            Wine - Magnotta, Merlot Sr Vqa    1
            Yoghurt Tubes                     1
Name: Quantity, Length: 288, dtype: int64

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [9]:
data_step6 = data_step5.groupby("ProductName").sum().sort_values(ascending=False)
data_step6

ProductName
Lettuce - Spring Mix                3
Fish - Scallops, Cold Smoked        3
Soupfoamcont12oz 112con             3
Wine - Two Oceans Cabernet          3
Bread - Italian Roll With Herbs     3
                                   ..
Onions - Vidalia                    1
Olive - Spread Tapenade             1
Oil - Shortening,liqud, Fry         1
Oil - Shortening - All - Purpose    1
Anchovy Paste - 56 G Tube           1
Name: Quantity, Length: 225, dtype: int64

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [10]:
custm_264 = table[264]
merged = pd.DataFrame.merge(custm_264, data_step6, how = 'left', on = 'ProductName')
merged.head()

264  Quantity
ProductName                                     
Anchovy Paste - 56 G Tube          0.0       1.0
Appetizer - Mini Egg Roll, Shrimp  0.0       1.0
Appetizer - Mushroom Tart          0.0       1.0
Appetizer - Sausage Rolls          0.0       1.0
Apricots - Dried                   0.0       2.0

In [14]:
data_step7 = merged.loc[(merged[264] == 0) & (merged.Quantity > 0)].sort_values(by=["Quantity"], ascending = False)
data_step7[:5]

264  Quantity
ProductName                                   
Soupfoamcont12oz 112con          0.0       3.0
Wine - Two Oceans Cabernet       0.0       3.0
Veal - Inside, Choice            0.0       3.0
Bread - Italian Roll With Herbs  0.0       3.0
Fondant - Icing                  0.0       3.0

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

In [17]:
# dict_recomm = {}
# set_custm = list(set(table.columns))
# for cust in set_custm:
#     #4  
#     similarities = matrix_df[cust].sort_values(ascending = False)[1:6]
#     lst_simi = list(similarities.index)

#     #5
#     data_step5 = data_step1.loc[lst_simi]

#     #6
#     data_step6 = data_step5.groupby("ProductName").sum().sort_values(ascending=False)

#     #7
#     custm_num = table[cust]
#     merged = pd.DataFrame.merge(custm_num, data_step6, how = 'left', on = 'ProductName')

#     data_step7 = merged.loc[(merged[cust] == 0) & (merged.Quantity > 0)].sort_values(by=["Quantity"], ascending = False)[:5]
    
#     dict_recomm[cust] = data_step7
    
dict_recomm = {}
set_custm = list(set(table.columns))
for cust in set_custm:
    #4  
    similarities = matrix_df[cust].sort_values(ascending = False)[1:6]
    lst_simi = list(similarities.index)

    #5
    data_step5 = data_step1.loc[lst_simi]

    #6
    data_step6 = data_step5.groupby("ProductName").sum().sort_values(ascending=False)

    #7
    custm_num = table[cust]
    merged = pd.DataFrame.merge(custm_num, data_step6, how = 'left', on = 'ProductName')

    data_step7 = merged.loc[(merged[cust] == 0) & (merged.Quantity > 0)].sort_values(by=["Quantity"], ascending = False)[:5]
    lst_top_5 = list(data_step7.index[:5])
    dict_recomm[cust] = lst_top_5  
    
    

In [18]:
dict_recomm[264]

['Soupfoamcont12oz 112con',
 'Wine - Two Oceans Cabernet',
 'Veal - Inside, Choice',
 'Bread - Italian Roll With Herbs',
 'Fondant - Icing']

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [20]:
big_daddy = pd.DataFrame(dict_recomm)
big_daddy.head()

83973                       49159  \
0           Cocoa Butter  Pasta - Penne, Rigate, Dry   
1      Veal - Slab Bacon          Cookies - Assorted   
2  Bandage - Fexible 1x3    Cheese - Parmesan Grated   
3   Ezy Change Mophandle               Puree - Mocha   
4  Pop Shoppe Cream Soda       Rice - Jasmine Sented   

                        22536                       18441  \
0         Cheese - Mozzarella     Soupfoamcont12oz 112con   
1  Bacardi Breezer - Tropical    Garlic - Primerba, Paste   
2            Chocolate - Dark  Lemonade - Natural, 591 Ml   
3  Table Cloth - 53x69 Colour         Sausage - Breakfast   
4             Banana - Leaves   Beef - Texas Style Burger   

                          59399                         92168  \
0     Shrimp - Baby, Warm Water  Cup - Translucent 7 Oz Clear   
1         Knife Plastic - White             Snapple Lemon Tea   
2        Towels - Paper / Kraft  Veal - Brisket, Provimi,bnls   
3  Nantucket - Pomegranate Pear         Pop Shoppe Cream Soda   
4    Cookie Chocolate Chip With                Spinach - Baby   

                           86028                       75791  \
0                 Spinach - Baby                 Blueberries   
1             Vinegar - Tarragon            Vaccum Bag 10x13   
2  Pork - Hock And Feet Attached  Turkey - Oven Roast Breast   
3      Orange - Canned, Mandarin        Mussels - Cultivated   
4           Bread Foccacia Whole  Bread - Calabrese Baguette   

                           96272                    32785  ...  \
0  Ecolab - Lime - A - Way 4/4 L       Cookies - Assorted  ...   
1                    Guinea Fowl  Table Cloth 54x72 White  ...   
2           Bread Crumbs - Panko           Juice - Orange  ...   
3             Sunflower Seed Raw        Juice - V8 Splash  ...   
4         Bread - English Muffin  Wine - Redchard Merritt  ...   

                       45042                        55281  \
0           Sea Bass - Whole             V8 - Berry Blend   
1  Ice Cream Bar - Oreo Cone  Pepper - Paprika, Hungarian   
2             Spinach - Baby      Soupcontfoam16oz 116con   
3        Beets - Mini Golden                 Brandy - Bar   
4  Anchovy Paste - 56 G Tube           Vinegar - Tarragon   

                              59379                      75762  \
0          Cod - Black Whole Fillet  Ice Cream Bar - Oreo Cone   
1  Pork - Back, Short Cut, Boneless               Vol Au Vents   
2               Thermometer Digital    Soupcontfoam16oz 116con   
3                       Beans - Wax           Ketchup - Tomato   
4       Sponge Cake Mix - Chocolate  Anchovy Paste - 56 G Tube   

                     77810                          16375  \
0  Olive - Spread Tapenade                        Mangoes   
1   Pants Custom Dry Clean         Beef - Chuck, Boneless   
2          Sword Pick Asst  Ice Cream Bar - Hageen Daz To   
3      Arizona - Green Tea        Rum - Mount Gay Eclipes   
4        Pail For Lid 1537            Sauce - Hollandaise   

                         77814                            20476  \
0  Cheese - Victor Et Berthold  Soup - Campbells Tomato Ravioli   
1             Sea Bass - Whole   Pasta - Detalini, White, Fresh   
2            Tilapia - Fillets                      Wanton Wrap   
3   Cake - Cake Sheet Macaroon   Wine - Magnotta, Merlot Sr Vqa   
4       Wine - Ruffino Chianti             Lime Cordial - Roses   

                     67582                           65535  
0   Cake - Mini Cheesecake                   Sauce - Rosee  
1    Ecolab - Solid Fusion            Scallop - St. Jaques  
2         Mussels - Frozen        Chestnuts - Whole,canned  
3  Wine - Redchard Merritt  Bread - Roll, Soft White Round  
4      Thermometer Digital               Chicken - Wieners  

[5 rows x 1000 columns]

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.

In [24]:
from scipy.spatial.distance import pdist, squareform
distances = pdist(table.T, 'cosine')
matrix = squareform(distances)
print(matrix)
matrix_df = pd.DataFrame(1/(1+squareform(pdist(table.T, 'euclidean'))), index = table.columns, columns=table.columns)

dict_recomm_cos = {}
set_custm = list(set(table.columns))
for cust in set_custm:
    #4  
    similarities = matrix_df[cust].sort_values(ascending = False)[1:6]
    lst_simi = list(similarities.index)

    #5
    data_step5 = data_step1.loc[lst_simi]

    #6
    data_step6 = data_step5.groupby("ProductName").sum().sort_values(ascending=False)

    #7
    custm_num = table[cust]
    merged = pd.DataFrame.merge(custm_num, data_step6, how = 'left', on = 'ProductName')

    data_step7 = merged.loc[(merged[cust] == 0) & (merged.Quantity > 0)].sort_values(by=["Quantity"], ascending = False)[:5]
    lst_top_5 = list(data_step7.index[:5])
    dict_recomm_cos[cust] = lst_top_5  

big_daddy_cos = pd.DataFrame(dict_recomm_cos)
big_daddy_cos.head()

[[0.         0.88678126 0.77464789 ... 0.9223069  0.88864251 0.89702036]
 [0.88678126 0.         0.86162154 ... 0.8612137  0.90053882 0.89652438]
 [0.77464789 0.86162154 0.         ... 0.85756266 0.80203113 0.89702036]
 ...
 [0.9223069  0.8612137  0.85756266 ... 0.         0.84074449 0.88165473]
 [0.88864251 0.90053882 0.80203113 ... 0.84074449 0.         0.83037577]
 [0.89702036 0.89652438 0.89702036 ... 0.88165473 0.83037577 0.        ]]


83973                       49159  \
0           Cocoa Butter  Pasta - Penne, Rigate, Dry   
1      Veal - Slab Bacon          Cookies - Assorted   
2  Bandage - Fexible 1x3    Cheese - Parmesan Grated   
3   Ezy Change Mophandle               Puree - Mocha   
4  Pop Shoppe Cream Soda       Rice - Jasmine Sented   

                        22536                       18441  \
0         Cheese - Mozzarella     Soupfoamcont12oz 112con   
1  Bacardi Breezer - Tropical    Garlic - Primerba, Paste   
2            Chocolate - Dark  Lemonade - Natural, 591 Ml   
3  Table Cloth - 53x69 Colour         Sausage - Breakfast   
4             Banana - Leaves   Beef - Texas Style Burger   

                          59399                         92168  \
0     Shrimp - Baby, Warm Water  Cup - Translucent 7 Oz Clear   
1         Knife Plastic - White             Snapple Lemon Tea   
2        Towels - Paper / Kraft  Veal - Brisket, Provimi,bnls   
3  Nantucket - Pomegranate Pear         Pop Shoppe Cream Soda   
4    Cookie Chocolate Chip With                Spinach - Baby   

                           86028                       75791  \
0                 Spinach - Baby                 Blueberries   
1             Vinegar - Tarragon            Vaccum Bag 10x13   
2  Pork - Hock And Feet Attached  Turkey - Oven Roast Breast   
3      Orange - Canned, Mandarin        Mussels - Cultivated   
4           Bread Foccacia Whole  Bread - Calabrese Baguette   

                           96272                    32785  ...  \
0  Ecolab - Lime - A - Way 4/4 L       Cookies - Assorted  ...   
1                    Guinea Fowl  Table Cloth 54x72 White  ...   
2           Bread Crumbs - Panko           Juice - Orange  ...   
3             Sunflower Seed Raw        Juice - V8 Splash  ...   
4         Bread - English Muffin  Wine - Redchard Merritt  ...   

                       45042                        55281  \
0           Sea Bass - Whole             V8 - Berry Blend   
1  Ice Cream Bar - Oreo Cone  Pepper - Paprika, Hungarian   
2             Spinach - Baby      Soupcontfoam16oz 116con   
3        Beets - Mini Golden                 Brandy - Bar   
4  Anchovy Paste - 56 G Tube           Vinegar - Tarragon   

                              59379                      75762  \
0          Cod - Black Whole Fillet  Ice Cream Bar - Oreo Cone   
1  Pork - Back, Short Cut, Boneless               Vol Au Vents   
2               Thermometer Digital    Soupcontfoam16oz 116con   
3                       Beans - Wax           Ketchup - Tomato   
4       Sponge Cake Mix - Chocolate  Anchovy Paste - 56 G Tube   

                     77810                          16375  \
0  Olive - Spread Tapenade                        Mangoes   
1   Pants Custom Dry Clean         Beef - Chuck, Boneless   
2          Sword Pick Asst  Ice Cream Bar - Hageen Daz To   
3      Arizona - Green Tea        Rum - Mount Gay Eclipes   
4        Pail For Lid 1537            Sauce - Hollandaise   

                         77814                            20476  \
0  Cheese - Victor Et Berthold  Soup - Campbells Tomato Ravioli   
1             Sea Bass - Whole   Pasta - Detalini, White, Fresh   
2            Tilapia - Fillets                      Wanton Wrap   
3   Cake - Cake Sheet Macaroon   Wine - Magnotta, Merlot Sr Vqa   
4       Wine - Ruffino Chianti             Lime Cordial - Roses   

                     67582                           65535  
0   Cake - Mini Cheesecake                   Sauce - Rosee  
1    Ecolab - Solid Fusion            Scallop - St. Jaques  
2         Mussels - Frozen        Chestnuts - Whole,canned  
3  Wine - Redchard Merritt  Bread - Roll, Soft White Round  
4      Thermometer Digital               Chicken - Wieners  

[5 rows x 1000 columns]

In [ ]:
# Han cambiado algunos valores de una a otra