# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [5]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [6]:
lista = [x for x in range(1,51)]
print (lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [7]:
listo = [x for x in range(2,201)]
print (listo)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200]


### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [8]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [9]:
liste = [i for x in a for i in x]
print (a)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [10]:
liste = [i for x in a for i in x if i >=0.5]
print (a)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [11]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [12]:
listu = [i for x in b for h in x for i in h]
print(listu)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [13]:
listy = [i[-1] for x in b for i in x if i[-1] <= 0.5]
print(listy)

[0.08147297, 0.06833034, 0.30296619, 0.45850679, 0.11434044, 0.10708681, 0.47984544, 0.23760688]


### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [14]:
ruta="../data"

archivos = [i for i in os.listdir(ruta) if i.endswith("csv")]
print(archivos)

['sample_file_9.csv', 'sample_file_7.csv', 'sample_file_2.csv', 'sample_file_1.csv', 'sample_file_4.csv', 'sample_file_6.csv', 'sample_file_5.csv', 'sample_file_3.csv', 'sample_file_8.csv', 'sample_file_0.csv']


### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [15]:
lista = [pd.read_csv(ruta+"/"+i) for i in os.listdir(ruta) if i.endswith("csv")]
resultado = pd.concat(lista)

resultado=resultado.reset_index(drop=True)

display(resultado.head(10))


0         1         2         3         4         5         6  \
0  0.215190  0.155352  0.160848  0.807736  0.363587  0.899832  0.146754   
1  0.895544  0.955196  0.089925  0.827555  0.089071  0.642883  0.996052   
2  0.413752  0.693052  0.789796  0.929164  0.536191  0.439769  0.773474   
3  0.728001  0.348156  0.935787  0.851163  0.444573  0.715080  0.988408   
4  0.134942  0.875931  0.273505  0.207588  0.080696  0.717396  0.033930   
5  0.460281  0.308551  0.735894  0.054059  0.593642  0.397679  0.019922   
6  0.065851  0.736029  0.797730  0.692722  0.167764  0.839756  0.910186   
7  0.671323  0.747296  0.892328  0.732902  0.065608  0.262364  0.712417   
8  0.445478  0.523522  0.959355  0.348292  0.761805  0.301391  0.712240   
9  0.291399  0.551248  0.736542  0.163562  0.451149  0.888938  0.968465   

          7         8         9        10        11        12        13  \
0  0.094802  0.705133  0.882762  0.773320  0.687745  0.016789  0.340725   
1  0.879020  0.421837  0.412141  0.858513  0.217091  0.176157  0.551236   
2  0.982074  0.876955  0.633154  0.279005  0.483317  0.908288  0.756172   
3  0.210332  0.732133  0.892383  0.216893  0.367595  0.846208  0.240111   
4  0.646837  0.888722  0.922742  0.176593  0.861333  0.389451  0.695244   
5  0.855673  0.339445  0.895810  0.832431  0.553308  0.617711  0.841575   
6  0.643328  0.371559  0.674311  0.424815  0.279397  0.015081  0.788497   
7  0.764379  0.017461  0.131970  0.649451  0.902157  0.034188  0.840938   
8  0.945462  0.139241  0.105477  0.889501  0.160828  0.400774  0.770295   
9  0.396090  0.681679  0.390542  0.030394  0.944077  0.366139  0.078188   

         14        15        16        17        18        19  
0  0.984182  0.985461  0.412044  0.867894  0.113432  0.349845  
1  0.834378  0.419535  0.041431  0.602258  0.984628  0.516899  
2  0.462130  0.289892  0.145233  0.076819  0.797836  0.197592  
3  0.471880  0.399721  0.758196  0.665568  0.931542  0.448124  
4  0.129955  0.364114  0.428224  0.365442  0.847818  0.588319  
5  0.336094  0.951907  0.050986  0.856135  0.773953  0.295344  
6  0.132391  0.766033  0.708510  0.752866  0.493862  0.577262  
7  0.098536  0.957824  0.566209  0.655947  0.592733  0.002596  
8  0.844655  0.772798  0.584262  0.807400  0.177419  0.926007  
9  0.175482  0.232489  0.806964  0.904593  0.803629  0.792851

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [17]:
import statistics as stats
medianas = resultado.median(axis = 0)
listamedias=[i for i in medianas if i <0.48]
listafinal=[]
for c in listamedias:
    listafinal.append([list(medianas).index(c)])
print(listafinal)

#Aqui he usado una lista de comprehension pero no como se supone que debería, voy a seguir y si me da tiempo lo corrijo


[[2], [9], [12], [14], [17]]


### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [31]:
y = []
[y.append(celdas-0.1) for celdas in resultado['19']]
    
resultado['20'] = [celdas - 0.1 for celdas in resultado['19']]
    
display(resultado.head(10))

0         1         2         3         4         5         6  \
0  0.215190  0.155352  0.160848  0.807736  0.363587  0.899832  0.146754   
1  0.895544  0.955196  0.089925  0.827555  0.089071  0.642883  0.996052   
2  0.413752  0.693052  0.789796  0.929164  0.536191  0.439769  0.773474   
3  0.728001  0.348156  0.935787  0.851163  0.444573  0.715080  0.988408   
4  0.134942  0.875931  0.273505  0.207588  0.080696  0.717396  0.033930   
5  0.460281  0.308551  0.735894  0.054059  0.593642  0.397679  0.019922   
6  0.065851  0.736029  0.797730  0.692722  0.167764  0.839756  0.910186   
7  0.671323  0.747296  0.892328  0.732902  0.065608  0.262364  0.712417   
8  0.445478  0.523522  0.959355  0.348292  0.761805  0.301391  0.712240   
9  0.291399  0.551248  0.736542  0.163562  0.451149  0.888938  0.968465   

          7         8         9  ...        11        12        13        14  \
0  0.094802  0.705133  0.882762  ...  0.687745  0.016789  0.340725  0.984182   
1  0.879020  0.421837  0.412141  ...  0.217091  0.176157  0.551236  0.834378   
2  0.982074  0.876955  0.633154  ...  0.483317  0.908288  0.756172  0.462130   
3  0.210332  0.732133  0.892383  ...  0.367595  0.846208  0.240111  0.471880   
4  0.646837  0.888722  0.922742  ...  0.861333  0.389451  0.695244  0.129955   
5  0.855673  0.339445  0.895810  ...  0.553308  0.617711  0.841575  0.336094   
6  0.643328  0.371559  0.674311  ...  0.279397  0.015081  0.788497  0.132391   
7  0.764379  0.017461  0.131970  ...  0.902157  0.034188  0.840938  0.098536   
8  0.945462  0.139241  0.105477  ...  0.160828  0.400774  0.770295  0.844655   
9  0.396090  0.681679  0.390542  ...  0.944077  0.366139  0.078188  0.175482   

         15        16        17        18        19        20  
0  0.985461  0.412044  0.867894  0.113432  0.349845  0.249845  
1  0.419535  0.041431  0.602258  0.984628  0.516899  0.416899  
2  0.289892  0.145233  0.076819  0.797836  0.197592  0.097592  
3  0.399721  0.758196  0.665568  0.931542  0.448124  0.348124  
4  0.364114  0.428224  0.365442  0.847818  0.588319  0.488319  
5  0.951907  0.050986  0.856135  0.773953  0.295344  0.195344  
6  0.766033  0.708510  0.752866  0.493862  0.577262  0.477262  
7  0.957824  0.566209  0.655947  0.592733  0.002596 -0.097404  
8  0.772798  0.584262  0.807400  0.177419  0.926007  0.826007  
9  0.232489  0.806964  0.904593  0.803629  0.792851  0.692851  

[10 rows x 21 columns]

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [41]:
#bet = [x for x in resultado if (x > 0.7 and x < 0.75)]
y = [i for i in resultado[x] for x in resultado if i > 0.7 and i < 0.75]

print(y)


[0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7033930409580709, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7274869207330491, 0.7376946446827494, 0.7376946446827494, 0.7376946446827494, 0.7376946446827494, 0.7376946446827494, 0.7376946446827494, 0.7376946446827494, 0.7376946446827494,