# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [2]:
print([n for n in range(1,51)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [3]:
print([n for n in range(1,201) if n%2==0])

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [4]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [5]:
print([g for grupo in a for g in grupo])

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [6]:
print([g for grupo in a for g in grupo if g >= 0.5])

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]


### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [7]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])
print(b)

[[[0.55867166 0.06210792 0.08147297]
  [0.82579068 0.91512478 0.06833034]]

 [[0.05440634 0.65857693 0.30296619]
  [0.06769833 0.96031863 0.51293743]]

 [[0.09143215 0.71893382 0.45850679]
  [0.58256464 0.59005654 0.56266457]]

 [[0.71600294 0.87392666 0.11434044]
  [0.8694668  0.65669313 0.10708681]]

 [[0.07529684 0.46470767 0.47984544]
  [0.65368638 0.14901286 0.23760688]]]


In [8]:
print([l for todo in b for lista in todo for l in lista])

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [9]:
print([lista[-1] for todo in b for lista in todo if lista[-1]<= 0.5])

[0.08147297, 0.06833034, 0.30296619, 0.45850679, 0.11434044, 0.10708681, 0.47984544, 0.23760688]


### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [10]:
#buscando mi directorio...
cwd = os.getcwd()
path = '../data'
#esto sería una forma de hacerlo con un bucle normal pero es una fórmula más enrevesada.
for root, dirs, files in os.walk(path):
    for file_name in files:
        if file_name.endswith('csv'):
            print(file_name)

#con list comprehension           
listacsv=[file for file in os.listdir('../data') if file.endswith('csv')]
print(listacsv)


sample_file_7.csv
sample_file_4.csv
sample_file_0.csv
sample_file_6.csv
sample_file_5.csv
sample_file_2.csv
sample_file_8.csv
sample_file_3.csv
sample_file_1.csv
sample_file_9.csv
['sample_file_7.csv', 'sample_file_4.csv', 'sample_file_0.csv', 'sample_file_6.csv', 'sample_file_5.csv', 'sample_file_2.csv', 'sample_file_8.csv', 'sample_file_3.csv', 'sample_file_1.csv', 'sample_file_9.csv']


### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [15]:
#aqui unimos todos los ficheros csv del directorio
todosficheros = [pd.read_csv(os.path.join('../data', file)) for file in listacsv]


In [25]:
#aqui los combinamos en un dataset
df = pd.concat(todosficheros, axis=0)
df.head(10)

0         1         2         3         4         5         6  \
0  0.460281  0.308551  0.735894  0.054059  0.593642  0.397679  0.019922   
1  0.065851  0.736029  0.797730  0.692722  0.167764  0.839756  0.910186   
2  0.671323  0.747296  0.892328  0.732902  0.065608  0.262364  0.712417   
3  0.445478  0.523522  0.959355  0.348292  0.761805  0.301391  0.712240   
4  0.291399  0.551248  0.736542  0.163562  0.451149  0.888938  0.968465   
0  0.901381  0.790944  0.596603  0.354721  0.357002  0.321325  0.738398   
1  0.763823  0.537281  0.708804  0.975269  0.053777  0.957740  0.389137   
2  0.571864  0.386243  0.567476  0.509283  0.552594  0.173807  0.229092   
3  0.956168  0.422274  0.121713  0.685208  0.713370  0.416245  0.337151   
4  0.121826  0.237479  0.553956  0.173660  0.354423  0.532080  0.271361   

          7         8         9        10        11        12        13  \
0  0.855673  0.339445  0.895810  0.832431  0.553308  0.617711  0.841575   
1  0.643328  0.371559  0.674311  0.424815  0.279397  0.015081  0.788497   
2  0.764379  0.017461  0.131970  0.649451  0.902157  0.034188  0.840938   
3  0.945462  0.139241  0.105477  0.889501  0.160828  0.400774  0.770295   
4  0.396090  0.681679  0.390542  0.030394  0.944077  0.366139  0.078188   
0  0.777885  0.775623  0.717817  0.788198  0.962214  0.394465  0.878922   
1  0.689829  0.510885  0.737445  0.097678  0.242906  0.073603  0.497591   
2  0.257945  0.313437  0.418311  0.750007  0.604759  0.234886  0.832337   
3  0.570693  0.435938  0.360098  0.037437  0.167545  0.847880  0.773456   
4  0.766006  0.607020  0.197302  0.526352  0.676571  0.473574  0.953228   

         14        15        16        17        18        19  
0  0.336094  0.951907  0.050986  0.856135  0.773953  0.295344  
1  0.132391  0.766033  0.708510  0.752866  0.493862  0.577262  
2  0.098536  0.957824  0.566209  0.655947  0.592733  0.002596  
3  0.844655  0.772798  0.584262  0.807400  0.177419  0.926007  
4  0.175482  0.232489  0.806964  0.904593  0.803629  0.792851  
0  0.084206  0.680941  0.992897  0.267455  0.212403  0.572150  
1  0.798467  0.789078  0.947559  0.631497  0.057953  0.060306  
2  0.421263  0.455785  0.893841  0.726412  0.458360  0.048740  
3  0.490628  0.544232  0.954668  0.567280  0.571539  0.560742  
4  0.413186  0.957242  0.642558  0.351496  0.547297  0.177401

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [27]:
selected_columns = [col for col in df._get_numeric_data() if df[col].median() < 0.48]
selected_columns

['2', '9', '12', '14', '17']

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [35]:
df['20'] = df['19'] - 0.1
df.head(10)

0         1         2         3         4         5         6  \
0  0.460281  0.308551  0.735894  0.054059  0.593642  0.397679  0.019922   
1  0.065851  0.736029  0.797730  0.692722  0.167764  0.839756  0.910186   
2  0.671323  0.747296  0.892328  0.732902  0.065608  0.262364  0.712417   
3  0.445478  0.523522  0.959355  0.348292  0.761805  0.301391  0.712240   
4  0.291399  0.551248  0.736542  0.163562  0.451149  0.888938  0.968465   
0  0.901381  0.790944  0.596603  0.354721  0.357002  0.321325  0.738398   
1  0.763823  0.537281  0.708804  0.975269  0.053777  0.957740  0.389137   
2  0.571864  0.386243  0.567476  0.509283  0.552594  0.173807  0.229092   
3  0.956168  0.422274  0.121713  0.685208  0.713370  0.416245  0.337151   
4  0.121826  0.237479  0.553956  0.173660  0.354423  0.532080  0.271361   

          7         8         9  ...        11        12        13        14  \
0  0.855673  0.339445  0.895810  ...  0.553308  0.617711  0.841575  0.336094   
1  0.643328  0.371559  0.674311  ...  0.279397  0.015081  0.788497  0.132391   
2  0.764379  0.017461  0.131970  ...  0.902157  0.034188  0.840938  0.098536   
3  0.945462  0.139241  0.105477  ...  0.160828  0.400774  0.770295  0.844655   
4  0.396090  0.681679  0.390542  ...  0.944077  0.366139  0.078188  0.175482   
0  0.777885  0.775623  0.717817  ...  0.962214  0.394465  0.878922  0.084206   
1  0.689829  0.510885  0.737445  ...  0.242906  0.073603  0.497591  0.798467   
2  0.257945  0.313437  0.418311  ...  0.604759  0.234886  0.832337  0.421263   
3  0.570693  0.435938  0.360098  ...  0.167545  0.847880  0.773456  0.490628   
4  0.766006  0.607020  0.197302  ...  0.676571  0.473574  0.953228  0.413186   

         15        16        17        18        19        20  
0  0.951907  0.050986  0.856135  0.773953  0.295344  0.195344  
1  0.766033  0.708510  0.752866  0.493862  0.577262  0.477262  
2  0.957824  0.566209  0.655947  0.592733  0.002596 -0.097404  
3  0.772798  0.584262  0.807400  0.177419  0.926007  0.826007  
4  0.232489  0.806964  0.904593  0.803629  0.792851  0.692851  
0  0.680941  0.992897  0.267455  0.212403  0.572150  0.472150  
1  0.789078  0.947559  0.631497  0.057953  0.060306 -0.039694  
2  0.455785  0.893841  0.726412  0.458360  0.048740 -0.051260  
3  0.544232  0.954668  0.567280  0.571539  0.560742  0.460742  
4  0.957242  0.642558  0.351496  0.547297  0.177401  0.077401  

[10 rows x 21 columns]

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.