# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [1]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [5]:
print([numbers for numbers in range(50)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [6]:
print([evens for evens in range(50) if evens %2 == 0])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [16]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [36]:
print(a)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


In [39]:
numpy_to_list = [y for e in a for y in e]
print(numpy_to_list)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [56]:
numpy_to_list = [y for e in a for y in e if y >= 0.5]
print(numpy_to_list)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]


### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [59]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [65]:
desanidar_3 = [des3 for des1 in b for des2 in des1 for des3 in des2]
print(desanidar_3)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [126]:
desanidar_4 = [des2[2] for des1 in b for des2 in des1 if des2[2] <= 0.5]
print(desanidar_4)

[0.08147297, 0.06833034, 0.30296619, 0.45850679, 0.11434044, 0.10708681, 0.47984544, 0.23760688]


### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [130]:
[filelist for filelist in os.listdir("../data") if ".csv" in filelist]

['sample_file_0.csv',
 'sample_file_1.csv',
 'sample_file_2.csv',
 'sample_file_3.csv',
 'sample_file_4.csv',
 'sample_file_5.csv',
 'sample_file_6.csv',
 'sample_file_7.csv',
 'sample_file_8.csv',
 'sample_file_9.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [192]:
filenames = [filelist for filelist in os.listdir("../data") if ".csv" in filelist]
fileslist = []
df = pd.concat([pd.read_csv("../data/"+filename) for filename in filenames], axis=0)
display(df.head(10))

0         1         2         3         4         5         6  \
0  0.734751  0.195362  0.734309  0.598184  0.763433  0.263434  0.868066   
1  0.772607  0.445391  0.249642  0.787922  0.598583  0.827238  0.624126   
2  0.226428  0.268764  0.694262  0.622335  0.063843  0.122683  0.815625   
3  0.362748  0.495430  0.113876  0.594149  0.612522  0.625204  0.864050   
4  0.033415  0.340433  0.464971  0.363737  0.025815  0.434129  0.415163   
0  0.276827  0.260054  0.942397  0.113187  0.781355  0.475740  0.152061   
1  0.995885  0.158381  0.244274  0.962163  0.651900  0.930665  0.577190   
2  0.641917  0.821055  0.392437  0.782617  0.510762  0.428320  0.017324   
3  0.806532  0.569258  0.148175  0.809987  0.459632  0.735762  0.730664   
4  0.311185  0.501165  0.365979  0.782807  0.776795  0.797199  0.791946   

          7         8         9        10        11        12        13  \
0  0.058092  0.753502  0.587513  0.311608  0.178356  0.182922  0.147631   
1  0.601524  0.688753  0.338870  0.081595  0.471474  0.267443  0.453351   
2  0.584542  0.032594  0.589775  0.764350  0.650973  0.565705  0.691784   
3  0.260279  0.528873  0.168043  0.715929  0.677014  0.175735  0.632370   
4  0.892210  0.381701  0.415264  0.790801  0.696930  0.819751  0.944029   
0  0.250324  0.147078  0.162984  0.977025  0.509619  0.593212  0.911839   
1  0.087914  0.960261  0.580840  0.194616  0.661459  0.674085  0.049326   
2  0.680720  0.340412  0.462513  0.785776  0.251949  0.032847  0.995700   
3  0.934502  0.080322  0.763502  0.398504  0.027637  0.409665  0.942846   
4  0.847157  0.771811  0.233944  0.522344  0.053030  0.208551  0.824354   

         14        15        16        17        18        19  
0  0.391188  0.816049  0.749068  0.293260  0.937828  0.880858  
1  0.800716  0.045749  0.683793  0.389789  0.016787  0.503695  
2  0.265223  0.739031  0.560394  0.334802  0.517694  0.646110  
3  0.926715  0.085675  0.120525  0.141746  0.771144  0.489660  
4  0.869965  0.041723  0.819140  0.676051  0.109349  0.872947  
0  0.257645  0.386457  0.696932  0.069162  0.952291  0.286542  
1  0.785803  0.315645  0.495355  0.232135  0.549324  0.572232  
2  0.816563  0.735692  0.435998  0.430411  0.531757  0.489528  
3  0.133256  0.157158  0.929446  0.402791  0.685976  0.246594  
4  0.588567  0.604341  0.232964  0.229109  0.022881  0.479022

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [197]:
selected_columns = [column for column in df if df[column].median() < 0.48]
print(selected_columns)

['2', '9', '12', '14', '17']


### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [247]:
col_20 = [col for col in df.iloc[:,19]]
df[20] = col_20
df[20] -= 0.1
display(df)

0         1         2         3         4         5         6  \
0   0.734751  0.195362  0.734309  0.598184  0.763433  0.263434  0.868066   
1   0.772607  0.445391  0.249642  0.787922  0.598583  0.827238  0.624126   
2   0.226428  0.268764  0.694262  0.622335  0.063843  0.122683  0.815625   
3   0.362748  0.495430  0.113876  0.594149  0.612522  0.625204  0.864050   
4   0.033415  0.340433  0.464971  0.363737  0.025815  0.434129  0.415163   
..       ...       ...       ...       ...       ...       ...       ...   
0   0.215190  0.155352  0.160848  0.807736  0.363587  0.899832  0.146754   
1   0.895544  0.955196  0.089925  0.827555  0.089071  0.642883  0.996052   
2   0.413752  0.693052  0.789796  0.929164  0.536191  0.439769  0.773474   
3   0.728001  0.348156  0.935787  0.851163  0.444573  0.715080  0.988408   
4   0.134942  0.875931  0.273505  0.207588  0.080696  0.717396  0.033930   

           7         8         9  ...        11        12        13        14  \
0   0.058092  0.753502  0.587513  ...  0.178356  0.182922  0.147631  0.391188   
1   0.601524  0.688753  0.338870  ...  0.471474  0.267443  0.453351  0.800716   
2   0.584542  0.032594  0.589775  ...  0.650973  0.565705  0.691784  0.265223   
3   0.260279  0.528873  0.168043  ...  0.677014  0.175735  0.632370  0.926715   
4   0.892210  0.381701  0.415264  ...  0.696930  0.819751  0.944029  0.869965   
..       ...       ...       ...  ...       ...       ...       ...       ...   
0   0.094802  0.705133  0.882762  ...  0.687745  0.016789  0.340725  0.984182   
1   0.879020  0.421837  0.412141  ...  0.217091  0.176157  0.551236  0.834378   
2   0.982074  0.876955  0.633154  ...  0.483317  0.908288  0.756172  0.462130   
3   0.210332  0.732133  0.892383  ...  0.367595  0.846208  0.240111  0.471880   
4   0.646837  0.888722  0.922742  ...  0.861333  0.389451  0.695244  0.129955   

          15        16        17        18        19        20  
0   0.816049  0.749068  0.293260  0.937828  0.880858  0.780858  
1   0.045749  0.683793  0.389789  0.016787  0.503695  0.403695  
2   0.739031  0.560394  0.334802  0.517694  0.646110  0.546110  
3   0.085675  0.120525  0.141746  0.771144  0.489660  0.389660  
4   0.041723  0.819140  0.676051  0.109349  0.872947  0.772947  
..       ...       ...       ...       ...       ...       ...  
0   0.985461  0.412044  0.867894  0.113432  0.349845  0.249845  
1   0.419535  0.041431  0.602258  0.984628  0.516899  0.416899  
2   0.289892  0.145233  0.076819  0.797836  0.197592  0.097592  
3   0.399721  0.758196  0.665568  0.931542  0.448124  0.348124  
4   0.364114  0.428224  0.365442  0.847818  0.588319  0.488319  

[50 rows x 21 columns]

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [299]:
y = []
between = [y for y in df[x] for x in df]
display(between)

NameError: name 'x' is not defined

In [298]:
df[1]

KeyError: 1